Show the new login form
silverstripe/silverstripe-userhelp-content pull request #163
Opened 2021-06-17 01:50 UTC by bergice

Resolves https://github.com/silverstripe/silverstripe-session-manager/pull/78

2021-06-21 21:46 UTC, maxime-rainville requested changes
Screenshot still says 90 days

2021-06-21 21:46 UTC, maxime-rainville commented on docs/en/01_Managing_your_website/01_Logging_In.md
> +If you’re having trouble accessing your account please contact the website owner.
```suggestion
If you’re having trouble accessing your account, contact the website owner.
```

2021-06-28 03:10 UTC, bergice commented
> Screenshot still says 90 days

That's fixed now.

2021-06-29 01:48 UTC, maxime-rainville approved these changes

2021-06-29 01:49 UTC, merged